set(LINUX False)

if (UNIX)
	set(LINUX True CACHE INTERNAL "Platform name")
endif()

if (ANDROID OR APPLE)
	set(LINUX False CACHE INTERNAL "Platform name")
endif()

if (WIN32)
	set(WI_PLATFORM_NAME "Windows" CACHE INTERNAL "Platform name")
elseif(LINUX)
	set(WI_PLATFORM_NAME "Linux" CACHE INTERNAL "Platform name")
elseif (APPLE)
	set(WI_PLATFORM_NAME "Apple" CACHE INTERNAL "Platform name")
elseif (ANDROID)
	set(WI_PLATFORM_NAME "Android" CACHE INTERNAL "Platform name")
else()
	set(WI_PLATFORM_NAME "Unknown" CACHE INTERNAL "Platform name")
	message(ERROR "Unknown platform")
endif()
