#pragma once

#define PREPROCESSOR_CONCAT_IMPL(x, y) x##y
#define PREPROCESSOR_CONCAT(x, y) PREPROCESSOR_CONCAT_IMPL(x, y)

#define PREPROCESSOR_STRINGIFY_IMPL(x) #x
#define PREPROCESSOR_STRINGIFY(x) PREPROCESSOR_STRINGIFY_IMPL(x)

#define BOOL_CAST(expr) (!!(expr))
